[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[package]
name = "hide-default-folders"
version = "0.1.0"
edition = "2021"

[dependencies]
winsafe = { version = "0.0.14", features = ["gui", "advapi"] }

[build-dependencies]
embed-manifest = "1.3.1"
